### ISSUE TITLE
Clarify How Custom Instances Are Configured

### ISSUE THREAD

**Issue by Airradda** [libreom/predirect#27]
It would be help if it clarified in the README or the configuration popup's field, `Custom Instance (Optional)`, what format the instance URL is supposed to be in. I was about ready to switch back to Libredirect as the addon was ignoring my custom instances and directing me to the same rate limited ones. It took me reading through the [code](https://github.com/libreom/predirect/blob/ca9d4b86d80f675eaf0a3f459983d1d759a40451/src/background.js#L61) to find that it should be `example.com` with no prefix or trailing slash and so you can't simply copy paste from the URL bar or a link.

**Comment by libreom** [comment]
Thanks for feedback, This is needed, what should be written in your opinion? For eg- "Custom Instance (eg- `nitter.net`)" or anything else. I'll clarify first in README, then in input area, and will also add validation and error handling it it's not written the right way

**Comment by Airradda** [comment]
Something like "Custom Instance (eg- nitter.net)" would work since I think "Custom" indicates it being optional pretty well.

**Comment by libreom** [comment]
Already Completed with https://github.com/libreom/predirect/commit/3ced4fc9a689cbedf0e9c6c882acac68b83b8900 It has not been released and likely won't be in a month, but one can give feedback by running extension from master branch or 
![image](https://github.com/libreom/predirect/assets/111110599/93ac0f7a-082b-4165-a468-9667fb1c186e)
