### ISSUE TITLE
Aehm... why is this offensive string the name that the firefox extension get's stored under?

### ISSUE THREAD

**Issue by TyberiusPrime** [libreom/predirect#36]
https://github.com/libreom/predirect/blob/661f3bae777a6d25ad6855db1ba98a11f9ac6b94/src/manifest-firefox.json#L62

**Comment by libreom** [comment]
Removed with https://github.com/libreom/predirect/commit/f0b691f8e525825b988d35243b56ed77f6d74530 It was temp id
